In [17]:
from PIL import Image
import numpy as np

im_frame = Image.open('companies.png')
np_frame = np.array(im_frame.getdata())

print (np_frame.shape)

(396270, 4)


In [18]:
import imageio

im = imageio.imread('companies.png')
print(im.shape)

(518, 765, 4)


In [ ]:
#cv - computer vision.

In [13]:
!pip install opencv-python

  Could not find a version that satisfies the requirement cv2 (from versions: )
No matching distribution found for cv2


In [30]:
import os
import matplotlib.pyplot as plt
import cv2
import numpy as np

# Get the file paths
im_files = os.curdir #os.listdir('path/to/files/')

# imagine we only want to load PNG files (or JPEG or whatever...)
EXTENSION = '.png'

# Load using matplotlib
images_plt = plt.imread("companies.png") #[plt.imread(f) for f in im_files if f.endswith(EXTENSION)]

# convert your lists into a numpy array of size (N, H, W, C)
images = np.array(images_plt)

# Load using opencv
images_cv = cv2.imread("companies.png") #[cv2.imread(f) for f in im_files if f.endswith(EXTENSION)]
# convert your lists into a numpy array of size (N, C, H, W)
images = np.array(images_cv)
print(images_plt.shape, images.shape)

(518, 765, 4) (518, 765, 3)


In [32]:
print (images)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 31 209 156]
  [ 31 209 156]
  [ 31 209 156]
  ...
  [ 31 209 156]
  [ 31 209 156]
  [ 31 209 156]]

 [[214 214 214]
  [211 211 211]
  [208 208 208]
  ...
  [203 203 203]
  [205 205 205]
  [208 208 208]]

 [[220 220 220]
  [218 218 218]
  [215 215 215]
  ...
  [210 210 210]
  [213 213 213]
  [215 215 215]]]


In [31]:
print (images_plt)

[[[1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]
  ...
  [1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]]

 [[1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]
  ...
  [1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]]

 [[1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]
  ...
  [1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]]

 ...

 [[0.6117647  0.81960785 0.12156863 1.        ]
  [0.6117647  0.81960785 0.12156863 1.        ]
  [0.61176